app/solution/__init__.py
from flask import Blueprint

solution = Blueprint('solution',__name__)

from . import views

app/solution/views.py
# -*- coding:utf-8 -*-
from . import solution
from flask import url_for,redirect,render_template,request,json
from flask_login import login_required,current_user
from ..models import Solution
from .. import db
from .form import SolutionForm

@solution.route('/subSolution',methods=['GET','POST'])
@solution.route('/subSolution/<int:creId>',methods=['GET','POST'])
@login_required
def subSolution(creId):
    if creId==None:
        return render_template('creativity.creativity')
    solutionForm = SolutionForm()
    if solutionForm.validate_on_submit():
        solutionItem = Solution(userId =current_user.userId,creativityId=creId,title = solutionForm.title.data,key_word=solutionForm.key_word.data
                                  ,type=int(solutionForm.type.data),describe=solutionForm.describe.data,state=1)
        db.session.add(solutionItem)
        db.session.commit()
        return redirect(url_for('.solution'))
    return render_template('solution/subSolution.html',form = solutionForm,creId=creId)


@solution.route('/solution_detail',methods=['GET'])
def solution_detail():
    solutionId = request.args.get('solutionId')
    solution = Solution.query.filter_by(solutionId=solutionId).first()
    if solution is None:
        return "并无该方案，服务器可能出错了"
    if solution.state != 2:
        solution.state = 2
        db.session.commit()
    dict={}
    dict['title'] = solution.title
    dict['key'] = solution.key_word
    dict['desc'] = solution.describe

    return render_template('/solution/solution_detail.html',dict=dict)

@solution.route('/accept_solution',methods=['GET'])
@login_required
def accept_solution():
    #现在要采纳该方案，就是把solution的state变为3
    solutionId = request.args.get('solutionId')
    solution = Solution.query.filter_by(solutionId=solutionId).first()
    solution.state = 3
    db.session.commit()
    return redirect(url_for('auth.auth_givensolution'))

@solution.route('/reject_solution',methods=['GET'])
@login_required
def reject_solution():
    #现在要拒绝该方案，就是把solution的state变为4
    solutionId = request.args.get('solutionId')
    solution = Solution.query.filter_by(solutionId=solutionId).first()
    solution.state = 4
    db.session.commit()
    return redirect(url_for('auth.auth_givensolution'))

@solution.route('/solution',methods=['GET'])
def solution():
    solutionList = Solution.query.order_by(Solution.solutionId.desc()).limit(4).all()
    dict={}
    typeDict = {1:u'software',2:u'hardware'}
    for i in range(len(solutionList)):
        dict[str(i+1)] = solutionList[i].solutionId
        dict['title'+str(i+1)] = solutionList[i].title
        dict['type' +str(i+1)] = typeDict[solutionList[i].type]
        dict['key'  +str(i+1)] = solutionList[i].key_word

    type1SolutionList=Solution.query.filter_by(type=1).order_by(Solution.solutionId.desc()).limit(4).all()
    dict_type1={}
    dict_type1['type1'] = 'software'
    for i in range(len(type1SolutionList)):
        dict_type1['title'+str(i+1)]=type1SolutionList[i].title

    type2SolutionList = Solution.query.filter_by(type=2).order_by(Solution.solutionId.desc()).limit(4).all()
    dict_type2 = {}
    dict_type2['type2'] = 'hardware'
    for i in range(len(type2SolutionList)):
        dict_type2['title' + str(i + 1)] = type2SolutionList[i].title

    recentSolutionList=Solution.query.filter_by(state=1).order_by(Solution.solutionId.desc()).limit(4).all()
    dict_recent={}
    for i in range(len(recentSolutionList)):
        dict_recent['title' + str(i + 1)] = recentSolutionList[i].title

    return render_template('solution/solution.html',dict=dict,dict_type1=dict_type1,dict_type2=dict_type2,dict_recent=dict_recent)

app/templates/solution/solution.html
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon" href="{{ url_for('static',filename='images/favicon.png') }}">
<title>在线任务智能匹配平台</title>

<!-- Bootstrap core CSS -->
<link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
<link rel="stylesheet" href="{{ url_for('static',filename='css/font-awesome.min.css') }}">
<!-- Custom styles for this template -->
<link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet">
<link href="{{ url_for('static',filename='css/sub.css')  }}" rel="stylesheet">
</head>
<!-- NAVBAR
================================================== -->
<body>
<input type="checkbox" class="eslint-toggle-search-checkbox" id="eslint-toggle-search">
<div class="navbar-wrapper">
  <div class="container">
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <label class="navbar-toggle eslint-toggle-search-open" for="eslint-toggle-search"> <span class="sr-only">Open search</span> <span aria-hidden="true" class="glyphicon glyphicon-search"></span> </label>
        <a class="navbar-brand logo" href="#"><img src="{{ url_for('static',filename='images/logo.png') }}" width="270" height="70"></a> </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">首页</a></li>
          <li><a href="{{ url_for('creativity.creativity')}}">创意集市</a></li>
          <li class="active"><a href="{{ url_for('solution.solution') }}">方案库</a></li>
          <li><a href="{{ url_for('product.product') }}">产品展示</a></li>
          <li><a href="{{ url_for('main.about') }}">俱乐部简介</a></li>
          <li><a href="http://mobiushacker.org/">俱乐部论坛</a></li>
          <!--<li><a href="{{ url_for('project.project') }}">大学生项目专区</a></li>-->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {%if not current_user.is_authenticated %}
          <li class="nav-signup-cta "> <a data-event-label="Signup Menu button / Header" data-event-action="click" data-event-category="Referral to Signup" href="{{ url_for('auth.register') }}">加入我们</a> </li>
          <li class=""> <a href="{{ url_for('auth.login') }}">登录</a> </li>
          {% else %}
                <li class="dropdown all-camera-dropdown">
                       <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <u>{{ current_user.username }}</u>
                           <b class="caret"></b>
                       </a>
                <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.user_Information_Save') }}">用户中心</a></li>
                        <li><a href="#">编辑资料</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
                 </ul></li>
            {% endif %}
          <!--<li classes="dropdown language-switch"> <span aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button" id="dLabel" classes="current-lang-btn"> 中文 <span classes="caret"></span> </span>
            <ul aria-labelledby="dLabel" classes="dropdown-menu">
              <li classes="lang-switcher-en preselected-lang"> <a href="/en" classes="lang-switch-en-">ENGLISH</a> </li>
              <li classes="lang-switcher-pl"> <a href="/pl" classes="lang-switch-pl-">中文</a> </li>
            </ul>
          </li>-->
        </ul>
        <label for="eslint-toggle-search" class="navbar-toggle eslint-toggle-search-open"> <span class="sr-only">Open search</span> <span class="glyphicon glyphicon-search" aria-hidden="true"></span> </label>
        <div class="navbar-form navbar-right eslint-search" role="search">
          <div class="input-group search-input-group">
            <!--label classes="sr-only" aria-label="Search" for="eslint-search-input">Search</label-->
            <div class="eslint-search-input-wrapper"> <span class="input-group-addon">
              <button type="submit"><span class="glyphicon glyphicon-search"></span></button>
              </span>
              <input type="text" class="form-control" id="eslint-search-input" accesskey="s" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" placeholder="搜索">
              <label for="eslint-toggle-search" class="eslint-toggle-search-close"> <span class="sr-only">Close search</span> <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span> </label>
            </div>
          </div>
        </div>
      </div>
    </div>
    </nav>
</div>
</div>
<div class="sub_title">
<div class="container">
<h2>方案库</h2>
</div>
</div>

<!-- Marketing messaging and featurettes
    ================================================== --> 
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container">
		<h3>最近中标</h3>
		<p>
            代表方案
		</p>
		<br>
		<ul class="list-unstyled video-list-thumbs row">
			<li class="col-lg-3 col-sm-4 col-xs-6">
				<a href="#" title="方案简介">
					<img src="{{ url_for('static',filename='images/portfolio/img1.jpg') }}" alt="Barca" class="img-responsive" height="130px">
					<h2>标题：{{ dict['title1'] }}<br> 类型：{{ dict['type1'] }}<br> 关键字：{{ dict['key1'] }}</h2>
					<span class="play-button"></span>
					<span class="duration">03:15</span>
				</a>
			</li>
			<li class="col-lg-3 col-sm-4 col-xs-6">
				<a href="#" title="方案简介">
					<img src="{{ url_for('static',filename='images/portfolio/img2.jpg') }}" alt="Barca" class="img-responsive" height="130px">
					<h2>标题：{{ dict['title2'] }}<br> 类型：{{ dict['type2'] }}<br> 关键字：{{ dict['key2'] }}</h2>
					<span class="play-button"></span>
					<span class="duration">03:15</span>
				</a>
			</li>
			<li class="col-lg-3 col-sm-4 col-xs-6">
				<a href="#" title="方案简介">
					<img src="{{ url_for('static',filename='images/portfolio/img3.jpg') }}" alt="Barca" class="img-responsive" height="130px">
					<h2>标题：{{ dict['title3'] }}<br> 类型：{{ dict['type3'] }}<br> 关键字：{{ dict['key3'] }}</h2>
					<span class="play-button"></span>
					<span class="duration">03:15</span>
				</a>
			</li>
			<li class="col-lg-3 col-md-4 col-sm-4 col-xs-6">
				<a href="#" title="方案简介">
					<img src="{{ url_for('static',filename='images/portfolio/img4.jpg') }}" alt="Barca" class="img-responsive" height="130px">
					<h2>标题：{{ dict['title4'] }}<br> 类型：{{ dict['type4'] }}<br> 关键字：{{ dict['key4'] }}</h2>
					<span class="play-button"></span>
					<span class="duration">03:15</span>
				</a>
			</li> 
		</ul>
	</div>
    <div id="courses">
		<section class="container">
			<h3>方案分类</h3>
			<div class="row">
				<div class="col-md-4">
					<div class="featured-box"> 
						<div class="text">
							<h3>{{ dict_type1['type1'] }}</h3>
							<p>{{ dict_type1['title1'] }} </p>
							<p>{{ dict_type1['title2'] }} </p>
							<p>{{ dict_type1['title3'] }} </p>
							<p><a href="#"><em>Read More</em></a></p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="featured-box"> 
						<div class="text">
							<h3>{{ dict_type2['type2'] }}</h3>
							<p>{{ dict_type2['title1'] }} </p>
							<p>{{ dict_type2['title2'] }} </p>
							<p>{{ dict_type2['title3'] }} </p>
							<p><a href="#"><em>Read More</em></a></p>							
						</div>
					</div>
				</div>			
				<!--<div classes="col-md-4">
					<div classes="featured-box">
						<div classes="text">
							<h3>计算机视觉</h3>
							<p>计算机视觉_方案1 </p>
							<p>计算机视觉_方案2 </p>
							<p>计算机视觉_方案3 </p>
							<p><a href="#"><em>Read More</em></a></p>		
						</div>
					</div>
				</div>
			</div>
			<div classes="row">
				<div classes="col-md-4">
					<div classes="featured-box">
						<div classes="text">
							<h3>机器学习</h3>
							<p>机器学习_方案1 </p>
							<p>机器学习_方案2 </p>
							<p>机器学习_方案3 </p>
							<p><a href="#"><em>Read More</em></a></p>									
						</div>
					</div>
				</div>
				<div classes="col-md-4">
					<div classes="featured-box">
						<div classes="text">
							<h3>三维建模技术</h3>
							<p>三维建模技术_方案1 </p>
							<p>三维建模技术_方案2 </p>
							<p>三维建模技术_方案3 </p>
							<p><a href="#"><em>Read More</em></a></p>								
						</div>
					</div>
				</div>
				<div classes="col-md-4">
					<div classes="featured-box">
						<div classes="text">
							<h3>语音识别和合成</h3>
							<p>语音识别和合成_方案1 </p>
							<p>语音识别和合成_方案2 </p>
							<p>语音识别和合成_方案3 </p>
							<p><a href="#"><em>Read More</em></a></p>									
						</div>
					</div>
				</div>
			</div>-->

		</section>
	</div>
    <div class="container">
		<div class="row">
			<!-- Article content -->
			<section class="col-sm-12 maincontent">
				<h3>最新提交</h3>
				<p>{{ dict_recent['title1'] }}	</p>
				<p>{{ dict_recent['title2'] }} </p>
				<p>{{ dict_recent['title3'] }} </p>
				<p>{{ dict_recent['title4'] }} </p>
				<!--<h3>线下活动</h3>
				<p>沈阳地区的树莓派爱好者多么？我们可以组织两次下线活动，一起交流交流啊！</p>
				<p>沈阳地区的树莓派爱好者多么？我们可以组织两次下线活动，一起交流交流啊！</p>
				<p>沈阳地区的树莓派爱好者多么？我们可以组织两次下线活动，一起交流交流啊！</p>-->
			</section>
		</div>
	</div>
<!-- /.container -->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="footerbottom">
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 创意集市 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li><a href="#"> 硬件设备 </a> </li>
                <li><a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li><a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 方案库 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li> <a href="#"> 硬件设备 </a> </li>
                <li><a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li><a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 产品展示 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li><a href="#"> 硬件设备 </a> </li>
                <li> <a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li> <a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4>联系我们</h4>
            <p>MBH树莓派智能机器人俱乐部</p>
            <div class="contact-info"> <i class="fa fa-map-marker"></i> 中国 辽宁 大连 滨海路风光栈道<br>
              <i class="fa fa-phone"></i> charles1245087438 <br>
              <i class="fa fa-envelope-o"></i> charlesliu2216@gmail.com </div>
          </div>
          <!-- end widget -->
        </div>
      </div>
    </div>
    <div class="social text-center"> <a href="#"><i class="fa fa-wechat"></i></a> <a href="#"><i class="fa fa-qq"></i></a> <a href="#"><i class="fa fa-weibo"></i></a> <a href="#"><i class="fa fa-git"></i></a> <a href="#"><i class="fa fa-envelope"></i></a> </div>
    <div class="clear"></div>
    <!--CLEAR FLOATS-->
  </div>
  <div class="footer2">
    <div class="container">
      <div class="row">
        <div class="col-md-6 panel">
          <div class="panel-body">
            <p class="simplenav"> <a href="/">首页</a> | <a href="{{ url_for('creativity.creativity') }}">创意集市</a> | <a href="{{ url_for('solution.solution') }}">方案库</a> | <a href="{{ url_for('product.product') }}">产品展示</a> | <a href="{{ url_for('main.about') }}">俱乐部简介</a> | <a href="http://mobiushacker.org/">俱乐部论坛</a> </p>
          </div>
        </div>
        <div class="col-md-6 panel">
          <div class="panel-body">
            <p class="text-right"> Copyright © 2016.MBHZB All rights reserved. </p>
          </div>
        </div>
      </div>
      <!-- /row of panels -->
    </div>
  </div>
</footer>
<a href="#top" class="topBtn"><i class="fa fa-angle-up"></i></a>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/custom.js') }}"></script>
</body>
</html>

app/templates/solution/subSolution.html
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon" href="{{ url_for('static',filename='images/favicon.png') }}">
<title>在线任务智能匹配平台</title>

<!-- Bootstrap core CSS -->
<link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
<link rel="stylesheet" href={{ url_for('static',filename='css/font-awesome.min.css') }}>
<!-- Custom styles for this template -->
<link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet">
<link href="{{ url_for('static',filename='css/sub.css') }}" rel="stylesheet">
</head>
<!-- NAVBAR
================================================== -->
<body>
<input type="checkbox" class="eslint-toggle-search-checkbox" id="eslint-toggle-search">
<div class="navbar-wrapper">
  <div class="container">
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <label class="navbar-toggle eslint-toggle-search-open" for="eslint-toggle-search"> <span class="sr-only">Open search</span> <span aria-hidden="true" class="glyphicon glyphicon-search"></span> </label>
        <a class="navbar-brand logo" href="#"><img src="{{ url_for('static',filename='images/logo.png') }}" width="270" height="70"></a> </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/">首页</a></li>
          <li><a href="{{ url_for('creativity.creativity')}}">创意集市</a></li>
          <li><a href="{{ url_for('solution.solution') }}">方案库</a></li>
          <li><a href="{{ url_for('product.product') }}">产品展示</a></li>
          <li><a href="{{ url_for('main.about') }}">俱乐部简介</a></li>
          <li><a href="http://mobiushacker.org/">俱乐部论坛</a></li>
          <!--<li><a href="{{ url_for('project.project') }}">大学生项目专区</a></li>-->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {%if not current_user.is_authenticated %}
          <li class="nav-signup-cta "> <a data-event-label="Signup Menu button / Header" data-event-action="click" data-event-category="Referral to Signup" href="{{ url_for('auth.register') }}">加入我们</a> </li>
          <li class=""> <a href="{{ url_for('auth.login') }}">登录</a> </li>
          {% else %}
                <li class="dropdown all-camera-dropdown">
                       <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <u>{{ current_user.username }}</u>
                           <b class="caret"></b>
                       </a>
                <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.user_Information_Save') }}">用户中心</a></li>
                        <li><a href="#">编辑资料</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
                 </ul></li>
            {% endif %}
          <!--<li classes="dropdown language-switch"> <span aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button" id="dLabel" classes="current-lang-btn"> 中文 <span classes="caret"></span> </span>
            <ul aria-labelledby="dLabel" classes="dropdown-menu">
              <li classes="lang-switcher-en preselected-lang"> <a href="/en" classes="lang-switch-en-">ENGLISH</a> </li>
              <li classes="lang-switcher-pl"> <a href="/pl" classes="lang-switch-pl-">中文</a> </li>
            </ul>
          </li>-->
        </ul>
        <label for="eslint-toggle-search" class="navbar-toggle eslint-toggle-search-open"> <span class="sr-only">Open search</span> <span class="glyphicon glyphicon-search" aria-hidden="true"></span> </label>
        <div class="navbar-form navbar-right eslint-search" role="search">
          <div class="input-group search-input-group">
            <!--label classes="sr-only" aria-label="Search" for="eslint-search-input">Search</label-->
            <div class="eslint-search-input-wrapper"> <span class="input-group-addon">
              <button type="submit"><span class="glyphicon glyphicon-search"></span></button>
              </span>
              <input type="text" class="form-control" id="eslint-search-input" accesskey="s" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" placeholder="搜索">
              <label for="eslint-toggle-search" class="eslint-toggle-search-close"> <span class="sr-only">Close search</span> <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span> </label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>
</div>



<!-- Marketing messaging and featurettes
    ================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->
<div class="container loginPannel">
                        <div class="row">
                            <div class="col-sm-6 b-r">
                                <form action="{{ url_for('solution.subSolution',creId=creId) }}" method="POST">
                                    {{ form.hidden_tag()}}
                                        <div class="from-group required">
                                            {{ form.title.label }}
                                            {{ form.title(class="form-control input-lg",required='')}}
                                            {% if form.title.errors %}
                                            <ul class="errors">{% for errors in form.title.errors %}<li>{{ error }}</li>{% endfor %}</ul>{% endif %}

                                        </div>
                                        <div class="form-group required">
                                            {{ form.type.label }}
                                            {{ form.type(class="form-control input-lg", required='') }}
                                            {% if form.type.errors %}
                                            <ul class="errors">{% for error in form.type.errors %}<li>{{ erros }}</li>{% endfor %}</ul>{% endif %}

                                        </div>
                                        <div class="from-group required">
                                            {{ form.key_word.label }}
                                            {{ form.key_word(class="form-control input-lg",required='')}}
                                            {% if form.key_word.errors %}
                                            <ul class="errors">{% for errors in form.key_word.errors %}<li>{{ error }}</li>{% endfor %}</ul>{% endif %}

                                        </div>
                                        <div class="from-group required">
                                            {{ form.describe.label }}
                                            {{ form.describe(class="form-control input-lg",required='')}}
                                            {% if form.describe.errors %}
                                            <ul class="errors">{% for errors in form.describe.errors %}<li>{{ error }}</li>{% endfor %}</ul>{% endif %}

                                        </div>
                                        {{ form.submit(class="btn btn-primary",value="提交") }}
                                </form>
                            </div>
                        </div>
                    </div>
<!-- /.container -->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="footerbottom">
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 创意集市 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li><a href="#"> 硬件设备 </a> </li>
                <li><a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li><a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 方案库 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li> <a href="#"> 硬件设备 </a> </li>
                <li><a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li><a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 产品展示 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li><a href="#"> 硬件设备 </a> </li>
                <li> <a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li> <a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4>联系我们</h4>
            <p>MBH树莓派智能机器人俱乐部</p>
            <div class="contact-info"> <i class="fa fa-map-marker"></i> 中国 辽宁 大连 滨海路风光栈道<br>
              <i class="fa fa-phone"></i> charles1245087438 <br>
              <i class="fa fa-envelope-o"></i> charlesliu2216@gmail.com </div>
          </div>
          <!-- end widget -->
        </div>
      </div>
    </div>
    <div class="social text-center"> <a href="#"><i class="fa fa-wechat"></i></a> <a href="#"><i class="fa fa-qq"></i></a> <a href="#"><i class="fa fa-weibo"></i></a> <a href="#"><i class="fa fa-git"></i></a> <a href="#"><i class="fa fa-envelope"></i></a> </div>
    <div class="clear"></div>
    <!--CLEAR FLOATS-->
  </div>
  <div class="footer2">
    <div class="container">
      <div class="row">
        <div class="col-md-6 panel">
          <div class="panel-body">
            <p class="simplenav"> <a href="index.html">首页</a> | <a href="creativity.html">创意集市</a> | <a href="solution.html">方案库</a> | <a href="product.html">产品展示</a> | <a href="about.html">俱乐部简介</a> | <a href="contact.html">俱乐部论坛</a> </p>
          </div>
        </div>
        <div class="col-md-6 panel">
          <div class="panel-body">
            <p class="text-right"> Copyright © 2016.MBHZB All rights reserved. </p>
          </div>
        </div>
      </div>
      <!-- /row of panels -->
    </div>
  </div>
</footer>
<a href="#top" class="topBtn"><i class="fa fa-angle-up"></i></a>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/custom.js') }}"></script>
</body>
</html>