app/project/__init__.py
from flask import Blueprint

project = Blueprint('project',__name__)

from . import views

app/project/views.py
# -*- coding:utf-8 -*-
from . import project
from flask import render_template,request,json,redirect,url_for,flash
from flask_login import login_required,current_user
from ..models import User_atten_project,Project,Solution,Project_Apply,User,Task
from .. import db
from .form import User_ProjectForm

@project.route('/project/attention',methods=['GET'])
@login_required
def attention():
    projectId = request.args.get('proId')
    u_a_p = User_atten_project.query.filter_by(userId=current_user.userId,projectId=projectId).first()
    if u_a_p is None:
        #说明要关注，添加进数据库
        u_a_p = User_atten_project(userId = current_user.userId,projectId=projectId)
        db.session.add(u_a_p)
        db.session.commit()
        return json.dumps({'success':True}),200,[('Content-Type','application/json;charset=utf-8')]
    else:
        #说明要取消关注，从数据库中删除该row
        db.session.delete(u_a_p)
        db.session.commit()
        return json.dumps({'success':True}),200,[('Content-Type','application/json;charset=utf-8')]

@project.route('/create_project',methods=['GET','POST'])
@login_required
def create_project():
    #2：实现申请加入项目（即改变项目的状态）

    #3同意后，生成对应 的 我的task条目
    #在我的task条目中改变任务状态
    if request.form['type'] == u'software':
        type = 1
    else: type = 2
    projectItem = Project(userId=current_user.userId,solutionId=request.form['solutionId'],
                          title=request.form['title'],type=type,
                          key_word=request.form['key_word'],describe=request.form['describe'],
                          state=1)
    db.session.add(projectItem)
    solution = Solution.query.filter_by(solutionId=request.form['solutionId']).first()
    solution.state = 5
    db.session.commit()
    projectItem = Project.query.filter_by(userId=current_user.userId,solutionId=request.form['solutionId']).first()
    projectId = projectItem.projectId
    return redirect(url_for('project.project_detail',projectId=projectId))

@project.route('/project_detail',methods=['GET'])
@login_required
def project_detail():
    projectId = request.args.get('projectId')
    dict={}
    if projectId==None:
        solutionId = request.args.get('solutionId')
        if solutionId==None:
            return u'服务器出现错误，请谅解！'
        projectItem = db.session.query(Project.title,Project.key_word,Project.describe)\
            .join(Solution).filter_by(solutionId=solutionId).first()
        print projectItem[0]
        dict['title'] = projectItem[0]
        dict['key'] = projectItem[1]
        dict['desc'] = projectItem[2]

        return render_template('/project/project_detail.html',dict=dict)
    projectItem = Project.query.filter_by(projectId=projectId).first()
    dict['title'] = projectItem.title
    dict['key'] = projectItem.key_word
    dict['desc'] = projectItem.describe

    return render_template('/project/project_detail.html',dict=dict)

@project.route('/join_now',methods=['GET','POST'])
@login_required
def join_Now():
    user_ProjectForm = User_ProjectForm()
    projectId = request.args.get('projectId')
    if projectId != None:
        user_ProjectForm.projectId.data = projectId
    if user_ProjectForm.validate_on_submit():
        #得到要申请加入的项目
        project_corr=Project.query.filter_by(projectId=user_ProjectForm.projectId.data).first()
        #申请理由存入数据库
        projectItem = Project_Apply(userId=current_user.userId,
                                    projectId=user_ProjectForm.projectId.data,
                                    reasons = user_ProjectForm.reasons.data,
                                    experience = user_ProjectForm.experience.data,
                                    note = user_ProjectForm.note.data,
                                    #既然能申请，说明项目此时并没有确定由谁负责
                                    state=1
                                    )
        db.session.add(projectItem)
        db.session.commit()
        #如果项目状态是1，则需要改变项目状态，否则不需要
        if project_corr.state == 1:
            project_corr.state=2
            # db.session.add(project_corr)
            db.session.commit()
        flash(u'you have applied!')
        return redirect(url_for('auth.auth_taskApply'))
    return render_template('/project/join_Now_Project.html',form=user_ProjectForm)

#点击‘有人申请’后触发
@project.route('/list_new',methods=['GET'])
@login_required
def list_new():
    projectId = request.args.get('projectId')
    #已经拒绝的项目不必再查看
    projectApplyList = db.session.query(User.username,Project_Apply.Id,Project_Apply.reasons,
                                        Project_Apply.experience,Project.title,
                                        Project_Apply.note).join(Project_Apply).\
        join(Project).filter(Project_Apply.state != 3).filter(Project_Apply.projectId==projectId).limit(3).all()

    dict = {}
    for i in range(len(projectApplyList)):
        dict['user' + str(i + 1)] = projectApplyList[i][0]
        dict['id'+str(i+1)]  = projectApplyList[i][1]
        dict['reasons' + str(i + 1)] = projectApplyList[i][2]
        dict['experience' + str(i + 1)] = projectApplyList[i][3]
        dict['projectTitle' + str(i + 1)] = projectApplyList[i][4]
        dict['note' + str(i + 1)] = projectApplyList[i][5]
    return render_template('/project/list_new.html',dict=dict)

# 1代表正在申请中（这是申请理由存入数据库的初始值 说明我要申请的这个项目还并没有任何人负责他，也就是项目的所有人还没有同意任何人）
# 2代表我已经成功被同意负责项目
# 3代表我申请的项目被别人加入了 我已经没机会负责了，或者是我直接被拒绝了，反正都是没机会参与项目了
@project.route('/admit',methods=['GET','POST'])
@login_required
def admit():
    #项目所有者同意以后，需要更改的信息有
    #申请状态（我的变为2，其他的变为3）
    #项目状态变为3
    #同时生成我的任务
    applyId = request.args.get('applyId')
    myApply = Project_Apply.query.filter_by(Id = applyId).first()
    projectApplyList = Project_Apply.query.filter_by(projectId = myApply.projectId).all()
    for i in range(len(projectApplyList)):
        projectApplyList[i].state = 3

        # db.session.add(projectApplyList[i])
    myApply.state = 2
    project_corr=Project.query.filter_by(projectId = myApply.projectId).first()
    project_corr.state = 3
    task_corr=Task(userId=myApply.userId,
                   title=project_corr.title,
                   projectId=project_corr.projectId,
                   type=project_corr.type,
                   key_word=project_corr.key_word,
                   describe=project_corr.describe,
                   state = 1
                   )
    db.session.add(task_corr)
    db.session.commit()
    flash(u'you have make your project beginning!')
    return redirect(url_for('auth.auth_project'))##404

@project.route('/reject',methods=['GET'])
@login_required
def reject():
    #点击拒绝后需要更改的信息有
    #我的申请状态变为3（因为我没机会参与项目了）
    applyId = request.args.get('applyId')
    myApply = Project_Apply.query.filter_by(Id = applyId).first()
    myApply.state = 3
    db.session.commit()
    return redirect(url_for('project.list_new'))


@project.route('/project')
def project():
    projectList = db.session.query(Project.projectId,Project.title,Project.describe)\
            .join(User).filter(User.type == 2).all()
    dict = {}
    for i in range(len(projectList)):
        dict['projectId' + str(i + 1)] = projectList[i][0]
        dict['projectTitle' + str(i + 1)] = projectList[i][1]
        dict['describe' + str(i + 1)] = projectList[i][2]
    return render_template('/project/project.html',dict=dict)

app/templates/project/list_new.html
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon" href="{{ url_for('static',filename='images/favicon.png') }}">
<title>在线任务智能匹配平台</title>

<!-- Bootstrap core CSS -->
<link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
<link rel="stylesheet" href="{{ url_for('static',filename='css/font-awesome.min.css') }}">
<!-- Custom styles for this template -->
<link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet">
<link href="{{ url_for('static',filename='css/sub.css') }}" rel="stylesheet">
<style>
.keleyitable {
width: 800px;
}

.keleyitable table, td, th {
border: 1px solid green;margin-top:10px;
}
.klytd {width:100px;text-align:right
}
.hvttd {
width:500px}
</style>

</head>
<body>
<input type="checkbox" class="eslint-toggle-search-checkbox" id="eslint-toggle-search">
<div class="navbar-wrapper">
  <div class="container">
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <label class="navbar-toggle eslint-toggle-search-open" for="eslint-toggle-search"> <span class="sr-only">Open search</span> <span aria-hidden="true" class="glyphicon glyphicon-search"></span> </label>
        <a class="navbar-brand logo" href="#"><img src="{{ url_for('static',filename='images/logo.png') }}" width="270" height="70"></a> </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/">首页</a></li>
          <li><a href="{{ url_for('creativity.creativity')}}">创意集市</a></li>
          <li><a href="{{ url_for('solution.solution') }}">方案库</a></li>
          <li><a href="{{ url_for('product.product') }}">产品展示</a></li>
          <li><a href="{{ url_for('main.about') }}">俱乐部简介</a></li>
          <li><a href="http://mobiushacker.org/">俱乐部论坛</a></li>
          <!--<li><a href="{{ url_for('project.project') }}">大学生项目专区</a></li>-->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {%if not current_user.is_authenticated %}
          <li class="nav-signup-cta "> <a data-event-label="Signup Menu button / Header" data-event-action="click" data-event-category="Referral to Signup" href="{{ url_for('auth.register') }}">加入我们</a> </li>
          <li class=""> <a href="{{ url_for('auth.login') }}">登录</a> </li>
          {% else %}
                <li class="dropdown all-camera-dropdown">
                       <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <u>{{ current_user.username }}</u>
                           <b class="caret"></b>
                       </a>
                <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.user_Information_Save') }}">用户中心</a></li>
                        <li><a href="#">编辑资料</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
                 </ul></li>
            {% endif %}
          <!--<li classes="dropdown language-switch"> <span aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button" id="dLabel" classes="current-lang-btn"> 中文 <span classes="caret"></span> </span>
            <ul aria-labelledby="dLabel" classes="dropdown-menu">
              <li classes="lang-switcher-en preselected-lang"> <a href="/en" classes="lang-switch-en-">ENGLISH</a> </li>
              <li classes="lang-switcher-pl"> <a href="/pl" classes="lang-switch-pl-">中文</a> </li>
            </ul>
          </li>-->
        </ul>
        <label for="eslint-toggle-search" class="navbar-toggle eslint-toggle-search-open"> <span class="sr-only">Open search</span> <span class="glyphicon glyphicon-search" aria-hidden="true"></span> </label>
        <div class="navbar-form navbar-right eslint-search" role="search">
          <div class="input-group search-input-group">
            <!--label classes="sr-only" aria-label="Search" for="eslint-search-input">Search</label-->
            <div class="eslint-search-input-wrapper"> <span class="input-group-addon">
              <button type="submit"><span class="glyphicon glyphicon-search"></span></button>
              </span>
              <input type="text" class="form-control" id="eslint-search-input" accesskey="s" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" placeholder="搜索">
              <label for="eslint-toggle-search" class="eslint-toggle-search-close"> <span class="sr-only">Close search</span> <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span> </label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>
</div>
<div class="sub_title">
<div class="container">
<h2>留言列表</h2>
</div>
</div>
<div style="margin:0px auto;" class="keleyitable">


<table>
<tr><td class="klytd">申请编号</td><td class="hvttd">{{ dict['id1']}}</td></tr>
<tr><td class="klytd">用户</td><td class="hvttd">{{ dict['user1']}}</td></tr>
<tr><td class="klytd">申请理由</td><td class ="hvttd">{{ dict['reasons1'] }}</td></tr>
<tr><td class="klytd">项目经历</td><td class ="hvttd">{{ dict['experience1'] }}</td></tr>
<tr><td class="klytd">要申请的任务</td><td class ="hvttd">{{ dict['projectTitle1'] }}</td></tr>
<tr><td class="klytd">备注</td><td class="hvttd">{{ dict['note1'] }}</td></tr>
</table>
    <a type="button" class="btn btn-success" href="{{ url_for('project.admit',applyId = dict['id1']) }}">同意</a>
    <a type="button" class="btn btn-success" href="{{ url_for('project.reject',applyId = dict['id1']) }}">拒绝</a>

<table class="table-responsive">
<tr><td class="klytd">申请编号</td><td class="hvttd">{{ dict['id2']}}</td></tr>
<tr><td class="klytd">用户</td><td class="hvttd">{{ dict['user2'] }}</td></tr>
<tr><td class="klytd">申请理由</td><td class ="hvttd">{{ dict['reasons2'] }}</td></tr>
<tr><td class="klytd">项目经历</td><td class ="hvttd">{{ dict['experience2'] }}</td></tr>
<tr><td class="klytd">要申请的任务</td><td class ="hvttd">{{ dict['projectTitle2'] }}</td></tr>
<tr><td class="klytd">备注</td><td class="hvttd">{{ dict['note2'] }}</td></tr>
</table>
    <a type="button" class="btn btn-success" href="{{ url_for('project.admit',applyId = dict['id2']) }}">同意</a>
    <a type="button" class="btn btn-success" href="{{ url_for('project.reject',applyId = dict['id1']) }}">拒绝</a>

<table>
<tr><td class="klytd">申请编号</td><td class="hvttd">{{ dict['id3']}}</td></tr>
<tr><td class="klytd">用户</td><td class="hvttd">{{ dict['user3'] }}</td></tr>
<tr><td class="klytd">申请理由</td><td class ="hvttd">{{ dict['reasons3'] }}</td></tr>
<tr><td class="klytd">项目经历</td><td class ="hvttd">{{ dict['experience3'] }}</td></tr>
<tr><td class="klytd">要申请的任务</td><td class ="hvttd">{{ dict['projectTitle'] }}</td></tr>
<tr><td class="klytd">备注</td><td class="hvttd">{{ dict['note3'] }}</td></tr>
</table>
    <a type="button" class="btn btn-success" href="{{ url_for('project.admit',applyId = dict['id3']) }}">同意</a>
    <a type="button" class="btn btn-success" href="{{ url_for('project.reject',applyId = dict['id1']) }}">拒绝</a>

</div>

<!-- /.container -->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="footerbottom">
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 创意集市 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li><a href="#"> 硬件设备 </a> </li>
                <li><a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li><a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 方案库 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li> <a href="#"> 硬件设备 </a> </li>
                <li><a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li><a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 产品展示 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li><a href="#"> 硬件设备 </a> </li>
                <li> <a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li> <a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4>联系我们</h4>
            <p>MBH树莓派智能机器人俱乐部</p>
            <div class="contact-info"> <i class="fa fa-map-marker"></i> 中国 辽宁 大连 滨海路风光栈道<br>
              <i class="fa fa-phone"></i> charles1245087438 <br>
              <i class="fa fa-envelope-o"></i> charlesliu2216@gmail.com </div>
          </div>
          <!-- end widget -->
        </div>
      </div>
    </div>
    <div class="social text-center"> <a href="#"><i class="fa fa-wechat"></i></a> <a href="#"><i class="fa fa-qq"></i></a> <a href="#"><i class="fa fa-weibo"></i></a> <a href="#"><i class="fa fa-git"></i></a> <a href="#"><i class="fa fa-envelope"></i></a> </div>
    <div class="clear"></div>
    <!--CLEAR FLOATS-->
  </div>
  <div class="footer2">
    <div class="container">
      <div class="row">
        <div class="col-md-6 panel">
          <div class="panel-body">
            <p class="simplenav"> <a href="/">首页</a> | <a href="{{ url_for('creativity.creativity') }}">创意集市</a> | <a href="{{ url_for('solution.solution') }}">方案库</a> | <a href="{{ url_for('product.product') }}">产品展示</a> | <a href="{{ url_for('main.about') }}">俱乐部简介</a> | <a href="http://mobiushacker.org/">俱乐部论坛</a> </p>
          </div>
        </div>
        <div class="col-md-6 panel">
          <div class="panel-body">
            <p class="text-right"> Copyright © 2016.MBHZB All rights reserved. </p>
          </div>
        </div>
      </div>
      <!-- /row of panels -->
    </div>
  </div>
</footer>
<a href="#top" class="topBtn"><i class="fa fa-angle-up"></i></a>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/custom.js') }}"></script>
</body>
</html>