app/creativity/__init__.py
from flask import Blueprint

creativity = Blueprint('creativity',__name__)
from . import views

app/creativity/views.py
# -*- coding:utf-8 -*-
from flask_login import login_required,current_user
from flask import url_for,redirect,render_template,request,json
from . import creativity
from .. import db
from .form import CreativityForm
from ..models import Creativity,User_atten_create,Solution

@creativity.route('/creativity/attention',methods=['GET'])
@login_required
def attention():
    creativityId = int(request.args.get('creId'))
    u_a_c = User_atten_create.query.filter_by(userId=current_user.userId,creativityId=creativityId).first()
    if u_a_c is None:
        #说明要关注，添加进数据库
        u_a_c = User_atten_create(userId = current_user.userId,creativityId=creativityId)
        db.session.add(u_a_c)
        db.session.commit()
        return json.dumps({'success':True}),200,[('Content-Type','application/json;charset=utf-8')]
    else:
        #说明要取消关注，从数据库中删除该row
        db.session.delete(u_a_c)
        db.session.commit()
        return json.dumps({'success':True}),200,[('Content-Type','application/json;charset=utf-8')]

@creativity.route('/subCreativity',methods=['GET','POST'])
@login_required
def subCreativity():
    creativityForm = CreativityForm()
    if creativityForm.validate_on_submit():

        #先设定提交成功后跳转到创意集市界面
        creativityItem = Creativity(userId =current_user.userId,title = creativityForm.title.data
                                  ,type=int(creativityForm.type.data),key_word=creativityForm.key_word.data
                                    ,describe=creativityForm.describe.data)
        db.session.add(creativityItem)
        db.session.commit()
        return redirect(url_for('.creativity'))
    return render_template('creativity/subCreativity.html',form = creativityForm)

@creativity.route('/creativity_detail',methods=['GET'])
@login_required
def creativity_detail():
    creativityId = request.args.get('creativityId')
    dict={}
    if creativityId==None:
        return u'服务器出现错误，请谅解！'
    creativityItem = Creativity.query.filter_by(creativityId=creativityId).first()
    dict['id']=creativityId
    dict['title'] = creativityItem.title
    dict['key'] = creativityItem.key_word
    dict['desc'] = creativityItem.describe
    solution_corr=Solution.query.filter_by(userId=current_user.userId,
                                creativityId=creativityId).first()
    if solution_corr:
        dict['solution'] = True
        dict['solutionId']=solution_corr.solutionId

    return render_template('/creativity/creativity_detail.html',dict=dict)

@creativity.route('/creativity',methods=['GET'])
def creativity():
    creativityList = Creativity.query.order_by(Creativity.creativityId.desc()).limit(12).all()
    dict = {}
    typeDict={1:u'software',2:u'hardware'}
    for i in range(len(creativityList)):
        dict[str(i+1)] = creativityList[i].creativityId
        dict['title'+str(i+1)] = creativityList[i].title
        dict['type' +str(i+1)] = typeDict[creativityList[i].type]
        dict['key'  +str(i+1)] = creativityList[i].key_word
    if current_user.is_authenticated:
        for i in range(len(creativityList)):
            if User_atten_create.query.filter_by(userId=current_user.userId,
                                                 creativityId=creativityList[i].creativityId).first():
                dict['follow'+str(i+1)] = True
            if Solution.query.filter_by(userId=current_user.userId,
                                        creativityId=creativityList[i].creativityId).first():
                dict['solution'+str(i+1)]=True

    return render_template('creativity/creativity.html',dict=dict)

app/templates/creativity/subCreativity.html
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon" href="{{ url_for('static',filename='images/favicon.png') }}">
<title>在线任务智能匹配平台</title>

<!-- Bootstrap core CSS -->
<link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
<link rel="stylesheet" href={{ url_for('static',filename='css/font-awesome.min.css') }}>
<!-- Custom styles for this template -->
<link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet">
<link href="{{ url_for('static',filename='css/sub.css') }}" rel="stylesheet">
</head>
<!-- NAVBAR
================================================== -->
<body>
<input type="checkbox" class="eslint-toggle-search-checkbox" id="eslint-toggle-search">
<div class="navbar-wrapper">
  <div class="container">
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <label class="navbar-toggle eslint-toggle-search-open" for="eslint-toggle-search"> <span class="sr-only">Open search</span> <span aria-hidden="true" class="glyphicon glyphicon-search"></span> </label>
        <a class="navbar-brand logo" href="#"><img src="{{ url_for('static',filename='images/logo.png') }}" width="270" height="70"></a> </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">首页</a></li>
          <li class="active"><a href="{{ url_for('creativity.creativity')}}">创意集市</a></li>
          <li><a href="{{ url_for('solution.solution') }}">方案库</a></li>
          <li><a href="{{ url_for('product.product') }}">产品展示</a></li>
          <li><a href="{{ url_for('main.about') }}">俱乐部简介</a></li>
          <li><a href="http://mobiushacker.org/">俱乐部论坛</a></li>
          <!--<li><a href="{{ url_for('project.project') }}">大学生项目专区</a></li>-->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {%if not current_user.is_authenticated %}
          <li class="nav-signup-cta "> <a data-event-label="Signup Menu button / Header" data-event-action="click" data-event-category="Referral to Signup" href="{{ url_for('auth.register') }}">加入我们</a> </li>
          <li class=""> <a href="{{ url_for('auth.login') }}">登录</a> </li>
          {% else %}
                <li class="dropdown all-camera-dropdown">
                       <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <u>{{ current_user.username }}</u>
                           <b class="caret"></b>
                       </a>
                <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.user_Information_Save') }}">用户中心</a></li>
                        <li><a href="#">编辑资料</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
                 </ul></li>
            {% endif %}
          <!--<li classes="dropdown language-switch"> <span aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button" id="dLabel" classes="current-lang-btn"> 中文 <span classes="caret"></span> </span>
            <ul aria-labelledby="dLabel" classes="dropdown-menu">
              <li classes="lang-switcher-en preselected-lang"> <a href="/en" classes="lang-switch-en-">ENGLISH</a> </li>
              <li classes="lang-switcher-pl"> <a href="/pl" classes="lang-switch-pl-">中文</a> </li>
            </ul>
          </li>-->
        </ul>
        <label for="eslint-toggle-search" class="navbar-toggle eslint-toggle-search-open"> <span class="sr-only">Open search</span> <span class="glyphicon glyphicon-search" aria-hidden="true"></span> </label>
        <div class="navbar-form navbar-right eslint-search" role="search">
          <div class="input-group search-input-group">
            <!--label classes="sr-only" aria-label="Search" for="eslint-search-input">Search</label-->
            <div class="eslint-search-input-wrapper"> <span class="input-group-addon">
              <button type="submit"><span class="glyphicon glyphicon-search"></span></button>
              </span>
              <input type="text" class="form-control" id="eslint-search-input" accesskey="s" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" placeholder="搜索">
              <label for="eslint-toggle-search" class="eslint-toggle-search-close"> <span class="sr-only">Close search</span> <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span> </label>
            </div>
          </div>
        </div>
      </div>
    </div>

  </nav>
</div>
</div>
<div class="sub_title">
<div class="container">
<h2>创意集市</h2>
</div>
</div>


<!-- Marketing messaging and featurettes
    ================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->
<div class="container loginPannel">
                        <div class="row">
                            <div class="col-sm-6 b-r">
                                <form action="{{url_for('creativity.subCreativity')}}" method="POST">
                                    {{ form.hidden_tag()}}
                                        <div class="from-group required">
                                            {{ form.title.label }}
                                            {{ form.title(class="form-control input-lg",required='')}}
                                            {% if form.title.errors %}
                                            <ul class="errors">{% for errors in form.title.errors %}<li>{{ error }}</li>{% endfor %}</ul>{% endif %}

                                        </div>
                                        <div class="form-group required">
                                            {{ form.type.label }}
                                            {{ form.type(class="form-control input-lg", required='') }}
                                            {% if form.type.errors %}
                                            <ul class="errors">{% for error in form.type.errors %}<li>{{ erros }}</li>{% endfor %}</ul>{% endif %}

                                        </div>
                                        <div class="from-group required">
                                            {{ form.key_word.label }}
                                            {{ form.key_word(class="form-control input-lg",required='')}}
                                            {% if form.key_word.errors %}
                                            <ul class="errors">{% for errors in form.key_word.errors %}<li>{{ error }}</li>{% endfor %}</ul>{% endif %}

                                        </div>
                                        <div class="from-group required">
                                            {{ form.describe.label }}
                                            {{ form.describe(class="form-control input-lg",required='')}}
                                            {% if form.describe.errors %}
                                            <ul class="errors">{% for errors in form.describe.errors %}<li>{{ error }}</li>{% endfor %}</ul>{% endif %}

                                        </div>
                                        {{ form.submit(class="btn btn-primary",value="提交") }}
                                </form>
                            </div>
                        </div>
                    </div>
<!-- /.container -->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="footerbottom">
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 创意集市 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li><a href="#"> 硬件设备 </a> </li>
                <li><a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li><a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 方案库 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li> <a href="#"> 硬件设备 </a> </li>
                <li><a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li><a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4> 产品展示 </h4>
            <div class="menu-course">
              <ul class="menu">
                <li><a href="#"> 硬件设备 </a> </li>
                <li> <a href="#"> 应用软件 </a> </li>
                <li><a href="#"> 支撑软件 </a> </li>
                <li> <a href="#"> 数据库系统 </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footerwidget">
            <h4>联系我们</h4>
            <p>MBH树莓派智能机器人俱乐部</p>
            <div class="contact-info"> <i class="fa fa-map-marker"></i> 中国 辽宁 大连 滨海路风光栈道<br>
              <i class="fa fa-phone"></i> charles1245087438 <br>
              <i class="fa fa-envelope-o"></i> charlesliu2216@gmail.com </div>
          </div>
          <!-- end widget -->
        </div>
      </div>
    </div>
    <div class="social text-center"> <a href="#"><i class="fa fa-wechat"></i></a> <a href="#"><i class="fa fa-qq"></i></a> <a href="#"><i class="fa fa-weibo"></i></a> <a href="#"><i class="fa fa-git"></i></a> <a href="#"><i class="fa fa-envelope"></i></a> </div>
    <div class="clear"></div>
    <!--CLEAR FLOATS-->
  </div>
  <div class="footer2">
    <div class="container">
      <div class="row">
        <div class="col-md-6 panel">
          <div class="panel-body">
            <p class="simplenav"> <a href="index.html">首页</a> | <a href="creativity.html">创意集市</a> | <a href="solution.html">方案库</a> | <a href="product.html">产品展示</a> | <a href="about.html">俱乐部简介</a> | <a href="contact.html">俱乐部论坛</a> </p>
          </div>
        </div>
        <div class="col-md-6 panel">
          <div class="panel-body">
            <p class="text-right"> Copyright © 2016.MBHZB All rights reserved. </p>
          </div>
        </div>
      </div>
      <!-- /row of panels -->
    </div>
  </div>
</footer>
<a href="#top" class="topBtn"><i class="fa fa-angle-up"></i></a>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/custom.js') }}"></script>
</body>
</html>